/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JOptionPane;

/**
 *
 * @author s.marcerou
 */
public class AddUserDialog extends javax.swing.JDialog {

    //attribue -------------------------------------------------------------------------------
    private PropertyChangeSupport listeners = new PropertyChangeSupport(this);

    // Constructeur -------------------------------------------------------------------------------
    public AddUserDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    // Methodes -------------------------------------------------------------------------------
    public void addPropertyChangeListener(PropertyChangeListener l) {
        this.listeners.addPropertyChangeListener(l);
    }

    // get -------------------------------------------------------------------------------
    public String getPrenom() {
        return this.addPrenomUser.getText();
    }

    public String getNom() {
        return this.addNomUser.getText();
    }

    public String getIdentifiant() {
        return this.addIdentifitantUser.getText();
    }

    public String getMotDePasse() {
        return this.addMotDePasseUser.getText();
    }

    public String getVerifMotDePasseUser() {
        return this.addVerifMotDePasseUser.getText();
    }

    public String getAdresseEmail() {
        return this.addEmailUser.getText();
    }

    // Set -------------------------------------------------------------------------------
    public void setPrenom(String prenom) {
        this.addPrenomUser.setText(prenom);
    }

    public void setNom(String nom) {
        this.addNomUser.setText(nom);
    }

    public void setIdentifiant(String identifiant) {
        this.addIdentifitantUser.setText(identifiant);
    }

    public void setMotDePasse(String motDePasse) {
        this.addMotDePasseUser.setText(motDePasse);
    }

    public void setVerifMotDePasseUser(String verifMdp) {
        this.addVerifMotDePasseUser.setText(verifMdp);
    }

    public void setAdresseEmail(String adresseEmail) {
        this.addEmailUser.setText(adresseEmail);
    }

    // Autre méthodes -------------------------------------------------------------------------------
    public boolean verifMotDePasse() {
        if (String.valueOf(this.addMotDePasseUser.getPassword()).equals(String.valueOf(this.addVerifMotDePasseUser.getPassword()))) {
            return true;
        } else {
            return false;
        }
    }

    public int verifeFormulaire() {
        String email = getAdresseEmail();
        if (addPrenomUser.getText().equals("")
                || addNomUser.getText().equals("")
                || addIdentifitantUser.getText().equals("")
                || addEmailUser.getText().equals("")
                || String.valueOf(this.addMotDePasseUser.getPassword()).equals("")) {
            return 1;
        } else if (!String.valueOf(this.addMotDePasseUser.getPassword()).equals(String.valueOf(this.addVerifMotDePasseUser.getPassword()))) {
            return 2;
        } else if (!isEmailValid(email)) {
            return 3;
        } else {
            return 4;
        }
    }

    public void erreurChamps() {
        JOptionPane.showMessageDialog(this, "Champs de saisie obligatoire !");
    }

    public void erreurMDP() {
        JOptionPane.showMessageDialog(this, "Vérification du mot de passe incorrect !");
    }

    public void erreurEmails() {
        JOptionPane.showMessageDialog(this, "Adresse email invalide.");
    }

    public boolean isEmailValid(String email) {
        return email.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$");
    }

    //set defaultData
    public void setDefaultData() {
        this.addPrenomUser.setText("");
        this.addNomUser.setText("");
        this.addIdentifitantUser.setText("");
        this.addMotDePasseUser.setText("");
        this.addVerifMotDePasseUser.setText("");
        this.addEmailUser.setText("");

        this.checkBoxAddAfficheNewMDP.setSelected(false);
        this.checkBoxAddAfficheVerifMDP.setSelected(false);

        this.addMotDePasseUser.setEchoChar('*');
        this.addVerifMotDePasseUser.setEchoChar('*');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        mpd = new javax.swing.JLabel();
        identifiant = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        ValideAjoutUser = new javax.swing.JButton();
        addPrenomUser = new javax.swing.JTextField();
        addNomUser = new javax.swing.JTextField();
        addIdentifitantUser = new javax.swing.JTextField();
        addEmailUser = new javax.swing.JTextField();
        jLabelPageAjoutUtilisateur = new javax.swing.JLabel();
        addMotDePasseUser = new javax.swing.JPasswordField();
        verifMdp = new javax.swing.JLabel();
        addVerifMotDePasseUser = new javax.swing.JPasswordField();
        checkBoxAddAfficheNewMDP = new javax.swing.JCheckBox();
        checkBoxAddAfficheVerifMDP = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        name.setText("Prenom");

        prenom.setText("Nom");

        mpd.setText("Mot-de-passe");

        identifiant.setText("Identifitant");

        mail.setText("Adresse mail");

        ValideAjoutUser.setText("Valider");
        ValideAjoutUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValideAjoutUserActionPerformed(evt);
            }
        });

        jLabelPageAjoutUtilisateur.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabelPageAjoutUtilisateur.setText("Page Ajout Utilisateur");

        verifMdp.setText("Verification mot-de-passe");

        checkBoxAddAfficheNewMDP.setText("Afficher le Mot de Passe");
        checkBoxAddAfficheNewMDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAddAfficheNewMDPActionPerformed(evt);
            }
        });

        checkBoxAddAfficheVerifMDP.setText("Afficher le Mot de Passe");
        checkBoxAddAfficheVerifMDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxAddAfficheVerifMDPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelPageAjoutUtilisateur))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prenom)
                            .addComponent(name)
                            .addComponent(identifiant)
                            .addComponent(mpd)
                            .addComponent(verifMdp)
                            .addComponent(mail))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ValideAjoutUser)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addNomUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addPrenomUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addIdentifitantUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addMotDePasseUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addVerifMotDePasseUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addEmailUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkBoxAddAfficheVerifMDP)
                                    .addComponent(checkBoxAddAfficheNewMDP))))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPageAjoutUtilisateur)
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addPrenomUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addNomUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prenom))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addIdentifitantUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(identifiant)))
                    .addComponent(name))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMotDePasseUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mpd)
                    .addComponent(checkBoxAddAfficheNewMDP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addVerifMotDePasseUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verifMdp)
                    .addComponent(checkBoxAddAfficheVerifMDP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mail))
                .addGap(18, 18, 18)
                .addComponent(ValideAjoutUser)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValideAjoutUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValideAjoutUserActionPerformed

        listeners.firePropertyChange("ValideAjoutUser", null, null);

    }//GEN-LAST:event_ValideAjoutUserActionPerformed

    private void checkBoxAddAfficheNewMDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAddAfficheNewMDPActionPerformed
        if (checkBoxAddAfficheNewMDP.isSelected()) {
            addMotDePasseUser.setEchoChar((char) 0);
        } else {
            addMotDePasseUser.setEchoChar('*');
        }
    }//GEN-LAST:event_checkBoxAddAfficheNewMDPActionPerformed

    private void checkBoxAddAfficheVerifMDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxAddAfficheVerifMDPActionPerformed
        if (checkBoxAddAfficheVerifMDP.isSelected()) {
            addVerifMotDePasseUser.setEchoChar((char) 0);
        } else {
            addVerifMotDePasseUser.setEchoChar('*');
        }
    }//GEN-LAST:event_checkBoxAddAfficheVerifMDPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddUserDialog dialog = new AddUserDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ValideAjoutUser;
    private javax.swing.JTextField addEmailUser;
    private javax.swing.JTextField addIdentifitantUser;
    private javax.swing.JPasswordField addMotDePasseUser;
    private javax.swing.JTextField addNomUser;
    private javax.swing.JTextField addPrenomUser;
    private javax.swing.JPasswordField addVerifMotDePasseUser;
    private javax.swing.JCheckBox checkBoxAddAfficheNewMDP;
    private javax.swing.JCheckBox checkBoxAddAfficheVerifMDP;
    private javax.swing.JLabel identifiant;
    private javax.swing.JLabel jLabelPageAjoutUtilisateur;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel mpd;
    private javax.swing.JLabel name;
    private javax.swing.JLabel prenom;
    private javax.swing.JLabel verifMdp;
    // End of variables declaration//GEN-END:variables
}
