/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JOptionPane;

/**
 *
 * @author e.zimmermann
 */
public class UpdateUserDialog extends javax.swing.JDialog {

    //attribue -------------------------------------------------------------------------------
    private int id;
    private PropertyChangeSupport listeners = new PropertyChangeSupport(this);

    // Constructeur -------------------------------------------------------------------------------
    public UpdateUserDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    // Methodes -------------------------------------------------------------------------------
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        listeners.addPropertyChangeListener(listener);
    }

    // get -------------------------------------------------------------------------------
    public int getId() {
        return this.id;
    }

    public String getPrenom() {
        return this.updatePrenomUser.getText();
    }

    public String getNom() {
        return this.updateNomUser.getText();
    }

    public String getIdentifiant() {
        return this.updateIdentifiantUser.getText();
    }

    public String getMotDePasse() {
        return this.updateMotDePasseUser.getText();
    }

    public String getVerifMotDePasseUser() {
        return this.updateVerifMotDePasseUser.getText();
    }

    public String getAdresseEmail() {
        return this.updateAdresseMailUser.getText();
    }

    // Set -------------------------------------------------------------------------------
    public void setID(int id) {
        this.id = id;
    }

    public void setPrenom(String prenom) {
        this.updatePrenomUser.setText(prenom);
    }

    public void setNom(String nom) {
        this.updateNomUser.setText(nom);
    }

    public void setIdentifiant(String identifiant) {
        this.updateIdentifiantUser.setText(identifiant);;
    }

    public void setMotDePasse(String mdp) {
        this.updateMotDePasseUser.setText(mdp);
    }

    public void setVerifMotDePasseUser(String verifMdp) {
        this.updateVerifMotDePasseUser.setText(verifMdp);
    }

    public void setAdresseEmail(String email) {
        this.updateAdresseMailUser.setText(email);
    }

    //set defaultData -------------------------------------------------------------------------------
    public void setDefaultData() {
        this.checkBoxModifAfficheNewMDP.setSelected(false);
        this.checkBoxModifAfficheVerifMDP.setSelected(false);

        this.updateVerifMotDePasseUser.setText("");

        this.updateMotDePasseUser.setEchoChar('*');
        this.updateVerifMotDePasseUser.setEchoChar('*');
    }

    // Autre méthodes -------------------------------------------------------------------------------
    public boolean verifMotDePasse() {
        if (String.valueOf(this.updateMotDePasseUser.getPassword()).equals(String.valueOf(this.updateVerifMotDePasseUser.getPassword()))) {
            return true;
        } else {
            return false;
        }
    }

    public int verifeFormulaire() {
        String email = getAdresseEmail();
        if (updatePrenomUser.getText().equals("")
                || updateNomUser.getText().equals("")
                || updateIdentifiantUser.getText().equals("")
                || updateAdresseMailUser.getText().equals("")
                || String.valueOf(this.updateMotDePasseUser.getPassword()).equals("")) {
            return 1;
        } else if (!String.valueOf(this.updateMotDePasseUser.getPassword()).equals(String.valueOf(this.updateVerifMotDePasseUser.getPassword()))) {
            return 2;
        } else if (!isEmailValid(email)) {
            return 3;
        } else {
            return 4;
        }
    }

    public void erreurChamps() {
        JOptionPane.showMessageDialog(this, "Champs de saisie obligatoire !");
    }

    public void erreurMDP() {
        JOptionPane.showMessageDialog(this, "Vérification du mot de passe incorrect !");
    }

    public void erreurEmails() {
        JOptionPane.showMessageDialog(this, "Adresse email invalide.");
    }

    public boolean isEmailValid(String email) {
        return email.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRetour = new javax.swing.JButton();
        jLabelPrenomUser = new javax.swing.JLabel();
        jLabelNomUser = new javax.swing.JLabel();
        jLabelIdentifiantUser = new javax.swing.JLabel();
        jLabelMotDePasseUser = new javax.swing.JLabel();
        jLabelAdresseEmailUser = new javax.swing.JLabel();
        jButtonValiderModif = new javax.swing.JButton();
        updatePrenomUser = new javax.swing.JTextField();
        updateIdentifiantUser = new javax.swing.JTextField();
        updateNomUser = new javax.swing.JTextField();
        updateAdresseMailUser = new javax.swing.JTextField();
        jLabelPageModifUtilisateur = new javax.swing.JLabel();
        updateMotDePasseUser = new javax.swing.JPasswordField();
        updateVerifMotDePasseUser = new javax.swing.JPasswordField();
        jLabelVerifMotDePasseUser = new javax.swing.JLabel();
        checkBoxModifAfficheVerifMDP = new javax.swing.JCheckBox();
        checkBoxModifAfficheNewMDP = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        jLabelPrenomUser.setText("Prenom");

        jLabelNomUser.setText("Nom");

        jLabelIdentifiantUser.setText("Identifiant");

        jLabelMotDePasseUser.setText("Mot-de-passe");

        jLabelAdresseEmailUser.setText("Adresse mail");

        jButtonValiderModif.setText("Valider");
        jButtonValiderModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderModifActionPerformed(evt);
            }
        });

        jLabelPageModifUtilisateur.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabelPageModifUtilisateur.setText("Page Modif Utilisateur");

        jLabelVerifMotDePasseUser.setText("Verification mot-de-passe");

        checkBoxModifAfficheVerifMDP.setText("Afficher le Mot de Passe");
        checkBoxModifAfficheVerifMDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxModifAfficheVerifMDPActionPerformed(evt);
            }
        });

        checkBoxModifAfficheNewMDP.setText("Afficher le Mot de Passe");
        checkBoxModifAfficheNewMDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxModifAfficheNewMDPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPageModifUtilisateur)
                .addGap(0, 361, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPrenomUser)
                            .addComponent(jLabelNomUser)
                            .addComponent(jLabelIdentifiantUser)
                            .addComponent(jLabelMotDePasseUser)))
                    .addComponent(jLabelVerifMotDePasseUser)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAdresseEmailUser)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateVerifMotDePasseUser)
                    .addComponent(updateNomUser)
                    .addComponent(updateIdentifiantUser)
                    .addComponent(updatePrenomUser)
                    .addComponent(updateAdresseMailUser)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonValiderModif)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRetour))
                    .addComponent(updateMotDePasseUser, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxModifAfficheVerifMDP)
                    .addComponent(checkBoxModifAfficheNewMDP))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPageModifUtilisateur)
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePrenomUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrenomUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateNomUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateIdentifiantUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdentifiantUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMotDePasseUser)
                    .addComponent(updateMotDePasseUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxModifAfficheNewMDP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateVerifMotDePasseUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVerifMotDePasseUser)
                    .addComponent(checkBoxModifAfficheVerifMDP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateAdresseMailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAdresseEmailUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValiderModif)
                    .addComponent(jButtonRetour))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void jButtonValiderModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderModifActionPerformed
        listeners.firePropertyChange("validModifUser", null, null);
    }//GEN-LAST:event_jButtonValiderModifActionPerformed

    private void checkBoxModifAfficheNewMDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxModifAfficheNewMDPActionPerformed
        if (checkBoxModifAfficheNewMDP.isSelected()) {
            updateMotDePasseUser.setEchoChar((char) 0);
        } else {
            updateMotDePasseUser.setEchoChar('*');
        }
    }//GEN-LAST:event_checkBoxModifAfficheNewMDPActionPerformed

    private void checkBoxModifAfficheVerifMDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxModifAfficheVerifMDPActionPerformed
        if (checkBoxModifAfficheVerifMDP.isSelected()) {
            updateVerifMotDePasseUser.setEchoChar((char) 0);
        } else {
            updateVerifMotDePasseUser.setEchoChar('*');
        }
    }//GEN-LAST:event_checkBoxModifAfficheVerifMDPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateUserDialog dialog = new UpdateUserDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxModifAfficheNewMDP;
    private javax.swing.JCheckBox checkBoxModifAfficheVerifMDP;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonValiderModif;
    private javax.swing.JLabel jLabelAdresseEmailUser;
    private javax.swing.JLabel jLabelIdentifiantUser;
    private javax.swing.JLabel jLabelMotDePasseUser;
    private javax.swing.JLabel jLabelNomUser;
    private javax.swing.JLabel jLabelPageModifUtilisateur;
    private javax.swing.JLabel jLabelPrenomUser;
    private javax.swing.JLabel jLabelVerifMotDePasseUser;
    private javax.swing.JTextField updateAdresseMailUser;
    private javax.swing.JTextField updateIdentifiantUser;
    private javax.swing.JPasswordField updateMotDePasseUser;
    private javax.swing.JTextField updateNomUser;
    private javax.swing.JTextField updatePrenomUser;
    private javax.swing.JPasswordField updateVerifMotDePasseUser;
    // End of variables declaration//GEN-END:variables
}
